# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 187)
        MainWindow.setStyleSheet("c")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.rotuloValidar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rotuloValidar.setFont(font)
        self.rotuloValidar.setObjectName("rotuloValidar")
        self.gridLayout.addWidget(self.rotuloValidar, 0, 0, 1, 1)
        self.inputValidar = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputValidar.setFont(font)
        self.inputValidar.setObjectName("inputValidar")
        self.gridLayout.addWidget(self.inputValidar, 0, 1, 1, 1)
        self.btnValidar = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidar.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnValidar.setFont(font)
        self.btnValidar.setObjectName("btnValidar")
        self.gridLayout.addWidget(self.btnValidar, 0, 2, 1, 1)
        self.rotuloGerador = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rotuloGerador.setFont(font)
        self.rotuloGerador.setObjectName("rotuloGerador")
        self.gridLayout.addWidget(self.rotuloGerador, 1, 0, 1, 1)
        self.btnGerar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGerar.setFont(font)
        self.btnGerar.setObjectName("btnGerar")
        self.gridLayout.addWidget(self.btnGerar, 1, 2, 1, 1)
        self.saidaResultado = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.saidaResultado.setFont(font)
        self.saidaResultado.setStyleSheet("color: green;")
        self.saidaResultado.setText("")
        self.saidaResultado.setAlignment(QtCore.Qt.AlignCenter)
        self.saidaResultado.setObjectName("saidaResultado")
        self.gridLayout.addWidget(self.saidaResultado, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPF Machine"))
        self.rotuloValidar.setText(_translate("MainWindow", "Validador de CPF"))
        self.btnValidar.setText(_translate("MainWindow", "VALIDAR"))
        self.rotuloGerador.setText(_translate("MainWindow", "Gerador de CPF"))
        self.btnGerar.setText(_translate("MainWindow", "GERAR"))
